### ISSUE TITLE
Marlin for plasma

### ISSUE THREAD

**Issue by mkeyno** [dbenamy/name-practice#1]
hi@dbenamy, I don't know whether still active on this project , but have you try to use marlin  to control THC or auto focus laser head module
BR

**Comment by dbenamy** [comment]
Is this the project you meant to ask about?

**Comment by mkeyno** [comment]
hi@dbenamy, actually I trace your work form[ this site ](http://opensourceecology.org/wiki/CNC_Torch_Table_2/Control_Overview) , on  control the THC with marlin , but my project is to make Marlin version for cutting cnc machine , which is tools in controlled by marlin , such as auto focus laser head and plasma THC 
I hope you still interested to this project and have your comments

**Comment by dbenamy** [comment]
Hi there! Feel free to email me at daniel at benamy dot info, or to join/email the list https://groups.google.com/forum/#!forum/ose-cnc-torch-table-development.

**Comment by mkeyno** [comment]
dear @dbenamy can you look at this [pull topic](https://github.com/MagoKimbra/MarlinKimbra/pull/113#issuecomment-204879376) for adding the laser to Marlin along with dynamically  Tools Height Control (THC) feature, really appreciated to have your comments or join it

**Comment by dbenamy** [comment]
That looks like a really cool projects and it's wonderful that you're contributing to it, but I'm afraid I don't have the context to be able to really review that. Hopefully the project maintainers can and will. Best of luck!
